# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/23858/AppData/Local/Temp/a3v_f1d817fbe2dd453583af22bc8a4c4e3d/ip_project/a3_fp32_ip_gen.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
# IP: The module: 'floating_point_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/23858/AppData/Local/Temp/a3v_f1d817fbe2dd453583af22bc8a4c4e3d/ip_project/a3_fp32_ip_gen.gen/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/23858/AppData/Local/Temp/a3v_f1d817fbe2dd453583af22bc8a4c4e3d/ip_project/a3_fp32_ip_gen.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
# IP: The module: 'floating_point_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/23858/AppData/Local/Temp/a3v_f1d817fbe2dd453583af22bc8a4c4e3d/ip_project/a3_fp32_ip_gen.gen/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
