create_clock -name core_clk -period 6.666 [get_ports clk]
set_property HD.CLK_SRC BUFGCE_X0Y0 [get_ports clk]
set_input_delay -clock core_clk -max 1.000 [get_ports -filter {DIRECTION == IN && NAME != clk}]
set_input_delay -clock core_clk -min 0.200 [get_ports -filter {DIRECTION == IN && NAME != clk}]
set_output_delay -clock core_clk -max 1.000 [get_ports -filter {DIRECTION == OUT}]
set_output_delay -clock core_clk -min -0.200 [get_ports -filter {DIRECTION == OUT}]
