# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/vivado_synth_bc_system/fpt_bc_ooc_synth.cache/wt [current_project]
set_property parent.project_path C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/vivado_synth_bc_system/fpt_bc_ooc_synth.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/vivado_synth_bc_system/fpt_bc_ooc_synth.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/softmax/exp_lut_q15.mem
read_verilog -library xil_defaultlib -sv {
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/backend/bf16_v_cache.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/adapter/causal_mask_stream.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/softmax/exp_lut.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/integration/gqa_group_controller.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/backend/pv_input_loader.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/qk_result_scaler.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/adapter/qk_softmax_adapter.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/integration/qk_softmax_frontend.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/integration/qk_softmax_pipeline_top.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/integration/qk_softmax_pv_pipeline_top.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/qk_systolic_gqa_top.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/qk_systolic_pe.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/qk_systolic_tile.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/adapter/score_rowtile_buffer.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/adapter/score_rowtile_payload_bram.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/softmax/softmax_bf16.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/backend/softmax_output_buffer.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/backend/softmax_pv_backend.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/softmax/unsigned_restoring_divider.sv
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/integration/qk_softmax_pv_system_top.sv
}
read_verilog -library xil_defaultlib {
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/bf16_to_fp32.v
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/fp32_add_ip.v
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/fp32_mul_ip.v
  C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/rtl/qk/fp32_to_bf16.v
}
read_ip -quiet c:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/vivado_synth_bc_system/fpt_bc_ooc_synth.srcs/sources_1/ip/floating_point_1/floating_point_1.xci

read_ip -quiet c:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/vivado_synth_bc_system/fpt_bc_ooc_synth.srcs/sources_1/ip/floating_point_2/floating_point_2.xci

read_ip -quiet c:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/vivado_synth_bc_system/fpt_bc_ooc_synth.srcs/sources_1/ip/floating_point_0/floating_point_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/constraints/qk_softmax_100mhz.xdc
set_property used_in_implementation false [get_files C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/constraints/qk_softmax_100mhz.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top qk_softmax_pv_system_top -part xc7a100tcsg324-1 -flatten_hierarchy none -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef qk_softmax_pv_system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file qk_softmax_pv_system_top_utilization_synth.rpt -pb qk_softmax_pv_system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
