# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/lhming/2_Work/4-FPT/FPT_BC_QK_Softmax_PV_Delivery_v5/constraints/qk_softmax_100mhz.xdc

# IP: ip/floating_point_1/floating_point_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1} -quiet] -quiet

# IP: ip/floating_point_2/floating_point_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_2 || ORIG_REF_NAME==floating_point_2} -quiet] -quiet

# IP: ip/floating_point_0/floating_point_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet
