# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/23858/AppData/Local/Temp/a3v_572b5181a6c64a459bb6726d090025d6/ip_project/a3_fp32_ip_gen.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/23858/AppData/Local/Temp/a3v_572b5181a6c64a459bb6726d090025d6/ip_project/a3_fp32_ip_gen.gen/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/23858/AppData/Local/Temp/a3v_572b5181a6c64a459bb6726d090025d6/ip_project/a3_fp32_ip_gen.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
# IP: The module: 'floating_point_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/23858/AppData/Local/Temp/a3v_572b5181a6c64a459bb6726d090025d6/ip_project/a3_fp32_ip_gen.gen/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
