# Rebuild the standalone RK-XCZU15EG-F V1.0 PL-DDR calibration and
# memory-self-test project from the board vendor's 10_DDR4_TEST assets.
#
# This script creates a Vivado GUI project only.  It does not launch
# simulation, synthesis, implementation, bitstream generation, or hardware
# programming.
#
# Default input location (prepared by ../scripts/prepare_vendor_assets.ps1):
#   ../generated/vendor_cache/pl_ddr_native/
#
# Optional overrides:
#   RK_PL_DDR_NATIVE_DIR  directory containing all five vendor assets
#   RK_PL_DDR_XCI         vendor DDR4 XCI
#   RK_MASTER_XDC         vendor pin.xdc
#   RK_PL_DDR_TOP         vendor top.v
#   RK_PL_DDR_MEM_TEST    vendor mem_test.v
#   RK_PL_DDR_MEM_BURST   vendor mem_burst.v

set script_dir [file normalize [file dirname [info script]]]
set system_root [file normalize [file join $script_dir ..]]
set project_dir [file normalize [file join $system_root vx pl_ddr]]
set project_name rk_pl_ddr
set part_name xczu15eg-ffvb1156-2-i
set vendor_xci_memory_part MT40A512M16HA-083E
set board_memory_marking LY-062E

proc env_or_default {name default_value} {
    if {[info exists ::env($name)] && $::env($name) ne ""} {
        return [file normalize $::env($name)]
    }
    return [file normalize $default_value]
}

proc require_file {label path} {
    if {![file isfile $path]} {
        error "BLOCKED: missing $label: $path\nRun system/scripts/prepare_vendor_assets.ps1 first, or provide the documented environment override."
    }
}

proc copy_asset {source_path destination_dir} {
    set destination [file join $destination_dir [file tail $source_path]]
    file copy -force $source_path $destination
    return [file normalize $destination]
}

# The vendor pin.xdc is an implementation-session export: its first section
# creates a large ILA and names implementation-specific nets.  Those commands
# are not portable across Vivado releases.  Extract only the board pin and
# explicit I/O-standard constraints; DDR electrical/timing constraints are
# generated by the DDR4 IP itself.
proc make_portable_pin_xdc {vendor_xdc portable_xdc} {
    set input_handle [open $vendor_xdc r]
    set output_handle [open $portable_xdc w]
    puts $output_handle "# Generated from the vendor RK-XCZU15EG-F V1.0 10_DDR4_TEST pin.xdc."
    puts $output_handle "# Only PACKAGE_PIN/IOSTANDARD commands are retained."
    puts $output_handle "# Legacy implementation-specific ILA commands are intentionally excluded."
    set retained 0
    set excluded 0
    while {[gets $input_handle line] >= 0} {
        if {[regexp {^\s*set_property\s+(PACKAGE_PIN|IOSTANDARD)\s+} $line]} {
            puts $output_handle $line
            incr retained
        } elseif {[string trim $line] ne ""} {
            incr excluded
        }
    }
    close $input_handle
    close $output_handle
    if {$retained < 60} {
        error "BLOCKED: portable pin extraction retained only $retained commands from $vendor_xdc"
    }
    return [list $retained $excluded]
}

set default_vendor_dir [file join $system_root generated vendor_cache pl_ddr_native]
set vendor_dir [env_or_default RK_PL_DDR_NATIVE_DIR $default_vendor_dir]
set source_xci [env_or_default RK_PL_DDR_XCI [file join $vendor_dir ddr4.xci]]
set source_xdc [env_or_default RK_MASTER_XDC [file join $vendor_dir pin.xdc]]
set source_top [env_or_default RK_PL_DDR_TOP [file join $vendor_dir top.v]]
set source_mem_test [env_or_default RK_PL_DDR_MEM_TEST [file join $vendor_dir mem_test.v]]
set source_mem_burst [env_or_default RK_PL_DDR_MEM_BURST [file join $vendor_dir mem_burst.v]]

foreach {label path} [list \
    "vendor DDR4 XCI" $source_xci \
    "vendor pin XDC" $source_xdc \
    "vendor self-test top" $source_top \
    "vendor memory checker" $source_mem_test \
    "vendor native-interface bridge" $source_mem_burst] {
    require_file $label $path
}

set xci_handle [open $source_xci r]
set xci_text [read $xci_handle]
close $xci_handle
set xci_memory_part UNKNOWN
regexp {PARAM_VALUE\.C0\.DDR4_MemoryPart">([^<]+)} $xci_text _ xci_memory_part
if {$xci_memory_part ne $vendor_xci_memory_part} {
    puts "WARNING: vendor XCI memory part is '$xci_memory_part'; expected archived vendor value '$vendor_xci_memory_part'."
}

if {[llength [get_projects -quiet]] > 0} {
    close_project
}
create_project $project_name $project_dir -part $part_name -force
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]
set_property source_mgmt_mode All [current_project]

# Work on project-local copies so upgrading the IP never modifies the ignored,
# hash-audited vendor cache.
set import_dir [file normalize [file join $project_dir vendor_native]]
set report_dir [file normalize [file join $project_dir reports]]
file mkdir $import_dir
file mkdir $report_dir
set local_xci [copy_asset $source_xci $import_dir]
set local_top [copy_asset $source_top $import_dir]
set local_mem_test [copy_asset $source_mem_test $import_dir]
set local_mem_burst [copy_asset $source_mem_burst $import_dir]
set local_vendor_xdc [copy_asset $source_xdc $import_dir]
set portable_xdc [file normalize [file join $import_dir rk_pl_ddr_pins.xdc]]
lassign [make_portable_pin_xdc $local_vendor_xdc $portable_xdc] retained_pin_commands excluded_xdc_commands

add_files -norecurse [list $local_top $local_mem_test $local_mem_burst]
# import_ip, unlike add_files/read_ip, copies the XCI into Vivado's managed
# project tree and rewrites its output location.  This prevents an archived
# 2020.2 path embedded in the vendor XCI from creating products elsewhere in
# the repository.
set managed_xci [file normalize [file join $project_dir ${project_name}.srcs sources_1 ip ddr4 ddr4.xci]]
if {[file isfile $managed_xci]} {
    file copy -force $local_xci $managed_xci
    add_files -norecurse $managed_xci
} else {
    set imported_ip_files [import_ip $local_xci -name ddr4]
    if {[llength $imported_ip_files] != 1} {
        error "BLOCKED: import_ip did not return exactly one managed DDR4 XCI"
    }
    set managed_xci [file normalize [get_property NAME [lindex $imported_ip_files 0]]]
}
add_files -fileset constrs_1 -norecurse $portable_xdc
set_property top top [get_filesets sources_1]
set_property top_auto_set 0 [get_filesets sources_1]
update_compile_order -fileset sources_1

set ddr_ips [get_ips -quiet ddr4]
if {[llength $ddr_ips] != 1} {
    error "BLOCKED: expected exactly one DDR4 IP named 'ddr4', found [llength $ddr_ips]"
}
set ddr_ip [lindex $ddr_ips 0]
set was_locked [get_property IS_LOCKED $ddr_ip]
if {$was_locked} {
    puts "INFO: upgrading the project-local DDR4 IP copy for Vivado [version -short]."
    upgrade_ip $ddr_ip
}
# Generate the synthesis products required by the RTL project.  Deliberately
# do not request the simulation target in this foundation phase.
generate_target synthesis $ddr_ip
update_compile_order -fileset sources_1

if {[get_property PART [current_project]] ne $part_name} {
    error "FAILED: generated project part is [get_property PART [current_project]], expected $part_name"
}
if {[get_property top [get_filesets sources_1]] ne "top"} {
    error "FAILED: generated project top is not vendor self-test module 'top'"
}

report_ip_status -file [file join $report_dir ip_status.txt]

set inventory_handle [open [file join $report_dir source_inventory.txt] w]
puts $inventory_handle "PROJECT_PART=[get_property PART [current_project]]"
puts $inventory_handle "PROJECT_TOP=[get_property top [get_filesets sources_1]]"
puts $inventory_handle "VIVADO_VERSION=[version -short]"
puts $inventory_handle "DDR4_IP_NAME=$ddr_ip"
puts $inventory_handle "DDR4_IP_DEFINITION=xilinx.com:ip:ddr4:2.2"
puts $inventory_handle "DDR4_IP_LOCKED=[get_property IS_LOCKED $ddr_ip]"
puts $inventory_handle "VENDOR_XCI_MEMORY_PART=$xci_memory_part"
puts $inventory_handle "BOARD_MEMORY_MARKING=$board_memory_marking"
puts $inventory_handle "MEMORY_PART_EQUIVALENCE=UNVERIFIED"
puts $inventory_handle "PORTABLE_PIN_COMMANDS=$retained_pin_commands"
puts $inventory_handle "EXCLUDED_LEGACY_XDC_COMMANDS=$excluded_xdc_commands"
puts $inventory_handle "HARDWARE_STATUS=HARDWARE_PENDING"
puts $inventory_handle "NOTE=init_calib_complete and error are MARK_DEBUG nets in top.v; insert/configure ILA after synthesis in the Vivado GUI."
puts $inventory_handle ""
puts $inventory_handle "PROJECT_FILES:"
foreach project_file [lsort [get_files -quiet]] {
    puts $inventory_handle $project_file
}
close $inventory_handle

set notice_handle [open [file join $project_dir PL_DDR_HARDWARE_NOTICE.txt] w]
puts $notice_handle "This project is generated from the RK-XCZU15EG-F V1.0 vendor 10_DDR4_TEST assets."
puts $notice_handle "Vendor XCI memory part: $xci_memory_part"
puts $notice_handle "Board DRAM marking documented for this project: $board_memory_marking"
puts $notice_handle "The two names are not identical. Electrical/timing equivalence has not been proven here."
puts $notice_handle "Project/IP generation is software evidence only; DDR calibration and memory correctness remain HARDWARE_PENDING."
puts $notice_handle "Do not report HARDWARE_PASS until init_calib_complete=1 and error=0 are observed on the physical board."
close $notice_handle

set xpr_path [file normalize [file join $project_dir ${project_name}.xpr]]
puts "RK_PL_DDR_PROJECT_READY=$xpr_path"
puts "RK_PL_DDR_INPUT_DIR=$vendor_dir"
puts "RK_PL_DDR_INPUT_MIG=$source_xci"
puts "RK_PL_DDR_INPUT_XDC=$source_xdc"
puts "RK_PL_DDR_XCI_MEMORY_PART=$xci_memory_part"
puts "RK_PL_DDR_BOARD_MEMORY_MARKING=$board_memory_marking"
puts "RK_PL_DDR_MEMORY_PART_EQUIVALENCE=UNVERIFIED"
puts "RK_PL_DDR_PORTABLE_PIN_COMMANDS=$retained_pin_commands"
puts "RK_PL_DDR_STATUS=PROJECT_READY_HARDWARE_CALIBRATION_PENDING"
close_project
