# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.runs/synth_1/attention_board_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu15eg-ffvb1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.cache/wt [current_project]
set_property parent.project_path D:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {QK_LANES=4 V_LANES=8 CAPTURE_TILE=4 PV_LANES=2} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/mem/exp_lut_q15.mem
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/mem/sin_bf16.hex
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/mem/cos_bf16.hex
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/backend/bf16_v_cache.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/softmax/exp_lut.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/online/flash_attention_consumer_top.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/a/flash_attention_system_with_rope_top.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/online/flash_context_fusion_backend.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/online/flash_context_update_pe.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/online/flash_online_softmax_frontend.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/online/flash_score_tile_fifo.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/board/fpt_attention_board_engine.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/board/fpt_context_ddr_writer.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/board/fpt_raw_qk_ddr_reader.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/board/fpt_v_ddr_loader.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/pv/pv_fp32_add_ip.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/pv/pv_fp32_mul_ip.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/online/qk_flash_attention_pipeline_top.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/qk_parallel_systolic_gqa_top.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/qk_result_scaler.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/qk_systolic_gqa_top.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/qk_systolic_pe.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/qk_systolic_tile.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/rope/rope_group_bridge.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/rope/rope_group_prepare.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/rope/rope_pair_pipeline.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/online/rope_qk_flash_attention_pipeline_top.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/rope/rope_qk_group_cache.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/softmax/unsigned_restoring_divider.sv
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/board/attention_board_top.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/board/aq_axi_master_fixed.v
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/bf16_to_fp32.v
  D:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/fp32_add_ip.v
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/fp32_mul_ip.v
  C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/rtl/core/bc/qk/fp32_to_bf16.v
}
add_files D:/fpt_build/v314/bd_staging/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_1/bd_ec3b_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_5/bd_ec3b_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_6/bd_ec3b_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_7/bd_ec3b_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_8/bd_ec3b_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_9/bd_ec3b_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_10/bd_ec3b_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_11/bd_ec3b_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_ctrl_0/design_1_axi_gpio_ctrl_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_ctrl_0/design_1_axi_gpio_ctrl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/design_1_ooc.xdc]

read_ip -quiet D:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.srcs/sources_1/ip/floating_point_0/floating_point_0.xci

read_ip -quiet D:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.srcs/sources_1/ip/floating_point_2/floating_point_2.xci

read_ip -quiet D:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.srcs/sources_1/ip/floating_point_1/floating_point_1.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/scripts/attention_board.xdc
set_property used_in_implementation false [get_files C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/scripts/attention_board.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top attention_board_top -part xczu15eg-ffvb1156-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef attention_board_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file attention_board_top_utilization_synth.rpt -pb attention_board_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
