# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/23858/xwechat_files/wxid_704fehcdj58l22_8fda/msg/file/2026-09/03_work_v314_causal_bypass/workspace/Llama3-8B-Attention-Optimize-ABL-v314/scripts/attention_board.xdc

# Block Designs: D:/fpt_build/v314/bd_staging/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: D:/fpt_build/v314/bd_staging/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: D:/fpt_build/v314/bd_staging/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: D:/fpt_build/v314/bd_staging/design_1/ip/design_1_axi_smc_ctrl_0/design_1_axi_smc_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_ctrl_0 || ORIG_REF_NAME==design_1_axi_smc_ctrl_0} -quiet] -quiet

# Block Designs: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/bd_ec3b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_1/bd_ec3b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_2/bd_ec3b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_3/bd_ec3b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_4/bd_ec3b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_5/bd_ec3b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_6/bd_ec3b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_7/bd_ec3b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_8/bd_ec3b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_9/bd_ec3b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_10/bd_ec3b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_11/bd_ec3b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_12/bd_ec3b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: D:/fpt_build/v314/bd_staging/design_1/ip/design_1_axi_gpio_ctrl_0/design_1_axi_gpio_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_ctrl_0 || ORIG_REF_NAME==design_1_axi_gpio_ctrl_0} -quiet] -quiet

# IP: ip/floating_point_0/floating_point_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0} -quiet] -quiet

# IP: ip/floating_point_2/floating_point_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_2 || ORIG_REF_NAME==floating_point_2} -quiet] -quiet

# IP: ip/floating_point_1/floating_point_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1} -quiet] -quiet

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_1/bd_ec3b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_5/bd_ec3b_s00a2s_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_6/bd_ec3b_sarn_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_7/bd_ec3b_srn_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_8/bd_ec3b_sawn_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_9/bd_ec3b_swn_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_10/bd_ec3b_sbn_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/bd_0/ip/ip_11/bd_ec3b_m00s2a_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_smc_ctrl_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_smc_ctrl_0 || ORIG_REF_NAME==design_1_axi_smc_ctrl_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_ctrl_0/design_1_axi_gpio_ctrl_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_ctrl_0 || ORIG_REF_NAME==design_1_axi_gpio_ctrl_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_ctrl_0/design_1_axi_gpio_ctrl_0_ooc.xdc

# XDC: d:/fpt_build/v314/fpt_attention_board_v314_qk4_causal_bypass/fpt_attention_board_v314_qk4_causal_bypass.gen/sources_1/bd/design_1/design_1_ooc.xdc
