`timescale 1ns/1ps
// Candidate CDC-to-writer bridge. Converts the existing output CDC row beat
// stream into the canonical 64-bit writer channel; no multi-bit CDC bypass.
module cats_r4_output_cdc_writer_candidate #(parameter int TOTAL_BEATS=32*128*4*8)(
 input logic core_clk,input logic core_rst_n,input logic core_counter_clear,input logic in_valid,output logic in_ready,input logic [15:0] in_epoch,input logic [4:0] in_global_q_head,input logic [6:0] in_row,input logic [1:0] in_feature_block,input logic [511:0] in_data_bf16,input logic in_row_last,input logic in_tensor_last,
 input logic axi_clk,input logic axi_rst_n,input logic axi_counter_clear,input logic start,input logic [31:0] base_addr,output logic wr_valid,input logic wr_ready,output logic [31:0] wr_addr,output logic [63:0] wr_data,output logic wr_row_last,output logic wr_tensor_last,output logic busy,output logic done,output logic error,output logic [63:0] protocol_error_count);
 logic ov,orx;logic [63:0] od;logic [15:0] oe;logic [11:0] os;logic [4:0] oh;logic [6:0] oy;logic [5:0] ob;logic orl,otl;logic [63:0] pp,pop,tp,top,fs,es,mp,mt,of,uf,seqe,ep;logic cpe,ape;
 cats_r4_output_cdc c(.core_clk,.core_rst_n,.core_counter_clear,.in_valid,.in_ready,.in_epoch,.in_global_q_head,.in_row,.in_feature_block,.in_data_bf16,.in_row_last,.in_tensor_last,.axi_clk,.axi_rst_n,.axi_counter_clear,.out_valid(ov),.out_ready(orx),.out_data(od),.out_epoch(oe),.out_seq(os),.out_global_q_head(oh),.out_row(oy),.out_beat_in_row(ob),.out_row_last(orl),.out_tensor_last(otl),.payload_push_count(pp),.payload_pop_count(pop),.tag_push_count(tp),.tag_pop_count(top),.full_stall_count(fs),.empty_stall_count(es),.max_payload_occupancy(mp),.max_tag_occupancy(mt),.overflow_count(of),.underflow_count(uf),.seq_error_count(seqe),.epoch_error_count(ep),.core_protocol_error(cpe),.axi_protocol_error(ape));
 cats_r4_output_writer_64 #(.TOTAL_BEATS(TOTAL_BEATS)) w(.clk(axi_clk),.rst_n(axi_rst_n),.clear(axi_counter_clear),.start,.base_addr,.in_valid(ov),.in_ready(orx),.in_epoch(oe),.in_seq(os),.in_global_q_head(oh),.in_row(oy),.in_feature_block(ob[4:3]),.in_beat_in_chunk(ob[2:0]),.in_data(od),.in_row_last(orl),.in_tensor_last(otl),.out_valid(wr_valid),.out_ready(wr_ready),.out_addr(wr_addr),.out_data(wr_data),.out_row_last(wr_row_last),.out_tensor_last(wr_tensor_last),.busy,.done,.error,.beats_accepted(),.rows_written(),.protocol_error_count());
 assign protocol_error_count=of|uf|seqe|ep|{63'd0,cpe|ape};
endmodule
