@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2018.3 (64-bit)
=======
REM Vivado (TM) v2019.2 (64-bit)
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Jul 20 18:32:23 +0800 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
=======
REM Generated by Vivado on Sat Jul 18 20:44:49 +0800 2026
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
REM
REM usage: compile.bat
REM
REM ****************************************************************************
echo "xvlog --incr --relax -prj tb_qk_softmax_pv_pipeline_small_vlog.prj"
call xvlog  --incr --relax -prj tb_qk_softmax_pv_pipeline_small_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
