@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2018.3 (64-bit)
=======
REM Vivado (TM) v2019.2 (64-bit)
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Jul 20 18:32:30 +0800 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
=======
REM Generated by Vivado on Sat Jul 18 20:44:52 +0800 2026
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xelab  -wto a1d0e4b1d35e4ad9a1d48e8b37510408 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_qk_softmax_pv_pipeline_small_behav xil_defaultlib.tb_qk_softmax_pv_pipeline_small xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab -wto 3e4e6424b9b947178efb1d79a84c6afd --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_qk_softmax_pv_pipeline_small_behav xil_defaultlib.tb_qk_softmax_pv_pipeline_small xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 3e4e6424b9b947178efb1d79a84c6afd --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_qk_softmax_pv_pipeline_small_behav xil_defaultlib.tb_qk_softmax_pv_pipeline_small xil_defaultlib.glbl -log elaborate.log
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
