@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2018.3 (64-bit)
=======
REM Vivado (TM) v2019.2 (64-bit)
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Mon Jul 20 18:32:47 +0800 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
=======
REM Generated by Vivado on Sat Jul 18 20:44:58 +0800 2026
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xsim tb_qk_softmax_pv_pipeline_small_behav -key {Behavioral:sim_1:Functional:tb_qk_softmax_pv_pipeline_small} -tclbatch tb_qk_softmax_pv_pipeline_small.tcl -log simulate.log
=======
echo "xsim tb_qk_softmax_pv_pipeline_small_behav -key {Behavioral:sim_1:Functional:tb_qk_softmax_pv_pipeline_small} -tclbatch tb_qk_softmax_pv_pipeline_small.tcl -log simulate.log"
call xsim  tb_qk_softmax_pv_pipeline_small_behav -key {Behavioral:sim_1:Functional:tb_qk_softmax_pv_pipeline_small} -tclbatch tb_qk_softmax_pv_pipeline_small.tcl -log simulate.log
>>>>>>> c3c9a3fb732fe4333d06b580e1017b39c4d3540b
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
