`timescale 1ns/1ps
module tb_cats_r4_weight_pv_mem_integration;
    logic clk=0; always #5 clk=~clk;
    logic rst_n=0, clear=0;
    logic start_valid,start_ready; logic [15:0] start_epoch; logic [2:0] start_group; logic [4:0] start_head; logic [6:0] start_row; logic [1:0] start_slot,start_mode; logic [31:0] start_sum,start_inv;
    logic [31:0] weights[0:511],case_weights[0:127]; logic [15:0] rows_mem[0:3]; logic [31:0] sums_mem[0:3],inv_sums_mem[0:3];
    logic ad_wr_valid,ad_wr_ready,ad_wr_mask,ad_wr_last; logic [15:0] ad_wr_epoch; logic [2:0] ad_wr_group; logic [4:0] ad_wr_head; logic [6:0] ad_wr_row,ad_wr_key; logic [1:0] ad_wr_slot,ad_wr_mode; logic [31:0] ad_wr_data;
    logic ad_commit_valid,ad_commit_ready; logic [15:0] ad_commit_epoch; logic [2:0] ad_commit_group; logic [4:0] ad_commit_head; logic [6:0] ad_commit_row; logic [1:0] ad_commit_slot,ad_commit_mode; logic [31:0] ad_commit_sum,ad_commit_inv;
    logic pv_row_valid,pv_row_ready; logic [15:0] pv_epoch; logic [2:0] pv_group; logic [4:0] pv_head; logic [6:0] pv_row; logic [1:0] pv_slot,pv_mode; logic [31:0] pv_sum,pv_inv;
    logic rd_valid,rd_ready,rd_rsp_valid; logic [15:0] rd_epoch,rsp_epoch; logic [2:0] rd_group,rsp_group; logic [4:0] rd_head,rsp_head; logic [6:0] rd_row,rd_key,rsp_row,rsp_key; logic [1:0] rd_slot,rd_mode,rsp_slot,rsp_mode; logic rsp_mask; logic [31:0] rsp_data;
    logic release_valid,release_ready; logic [15:0] rel_epoch; logic [2:0] rel_group; logic [4:0] rel_head; logic [6:0] rel_row; logic [1:0] rel_slot,rel_mode;
    logic [63:0] wr_accept,rd_request,rd_response,row_commits,pv_rows,releases,owner_error,mask_error,last_error,mode_error,numeric_error,epoch_drop,bank_conflict,outstanding_max;
    logic row_start_valid,row_start_ready; logic [31:0] row_start_inv_sum; logic weight_valid,weight_ready; logic [6:0] weight_key; logic weight_mask; logic [31:0] weight_data; logic weight_last; logic pv_done_valid,pv_done_ready; logic wrapper_release_valid,wrapper_release_ready; logic [15:0] wrapper_rel_epoch; logic [2:0] wrapper_rel_group; logic [4:0] wrapper_rel_head; logic [6:0] wrapper_rel_row; logic [1:0] wrapper_rel_slot,wrapper_rel_mode; logic [63:0] rows_started,weights_forwarded,rows_released,wrapper_errors;

    cats_r4_if_v3_replay_adapter u_ad (.clk,.rst_n,.clear,.start_valid,.start_ready,.start_epoch,.start_group,.start_global_q_head(start_head),.start_row,.start_slot_id(start_slot),.start_numeric_mode(start_mode),.start_sum_fp32(start_sum),.start_inv_sum_fp32(start_inv),.weight_wr_valid(ad_wr_valid),.weight_wr_ready(ad_wr_ready),.weight_wr_epoch(ad_wr_epoch),.weight_wr_group(ad_wr_group),.weight_wr_global_q_head(ad_wr_head),.weight_wr_row(ad_wr_row),.weight_wr_slot_id(ad_wr_slot),.weight_wr_numeric_mode(ad_wr_mode),.weight_wr_key(ad_wr_key),.weight_wr_mask(ad_wr_mask),.weight_wr_data(ad_wr_data),.weight_wr_last(ad_wr_last),.row_commit_valid(ad_commit_valid),.row_commit_ready(ad_commit_ready),.row_commit_epoch(ad_commit_epoch),.row_commit_group(ad_commit_group),.row_commit_global_q_head(ad_commit_head),.row_commit_row(ad_commit_row),.row_commit_slot_id(ad_commit_slot),.row_commit_numeric_mode(ad_commit_mode),.row_commit_sum_fp32(ad_commit_sum),.row_commit_inv_sum_fp32(ad_commit_inv),.weight_data(case_weights));
    cats_r4_weight_slot_mem u_mem (.clk,.rst_n,.clear,.weight_wr_valid(ad_wr_valid),.weight_wr_ready(ad_wr_ready),.weight_wr_epoch(ad_wr_epoch),.weight_wr_group(ad_wr_group),.weight_wr_global_q_head(ad_wr_head),.weight_wr_row(ad_wr_row),.weight_wr_slot_id(ad_wr_slot),.weight_wr_numeric_mode(ad_wr_mode),.weight_wr_key(ad_wr_key),.weight_wr_mask(ad_wr_mask),.weight_wr_data(ad_wr_data),.weight_wr_last(ad_wr_last),.row_commit_valid(ad_commit_valid),.row_commit_ready(ad_commit_ready),.row_commit_epoch(ad_commit_epoch),.row_commit_group(ad_commit_group),.row_commit_global_q_head(ad_commit_head),.row_commit_row(ad_commit_row),.row_commit_slot_id(ad_commit_slot),.row_commit_numeric_mode(ad_commit_mode),.row_commit_sum_fp32(ad_commit_sum),.row_commit_inv_sum_fp32(ad_commit_inv),.pv_row_valid,.pv_row_ready,.pv_row_epoch(pv_epoch),.pv_row_group(pv_group),.pv_row_global_q_head(pv_head),.pv_row_row(pv_row),.pv_row_slot_id(pv_slot),.pv_row_numeric_mode(pv_mode),.pv_row_sum_fp32(pv_sum),.pv_row_inv_sum_fp32(pv_inv),.weight_rd_req_valid(rd_valid),.weight_rd_req_ready(rd_ready),.weight_rd_req_epoch(rd_epoch),.weight_rd_req_group(rd_group),.weight_rd_req_global_q_head(rd_head),.weight_rd_req_row(rd_row),.weight_rd_req_slot_id(rd_slot),.weight_rd_req_numeric_mode(rd_mode),.weight_rd_req_key(rd_key),.weight_rd_rsp_valid(rd_rsp_valid),.weight_rd_rsp_epoch(rsp_epoch),.weight_rd_rsp_group(rsp_group),.weight_rd_rsp_global_q_head(rsp_head),.weight_rd_rsp_row(rsp_row),.weight_rd_rsp_slot_id(rsp_slot),.weight_rd_rsp_numeric_mode(rsp_mode),.weight_rd_rsp_key(rsp_key),.weight_rd_rsp_mask(rsp_mask),.weight_rd_rsp_data(rsp_data),.weight_release_valid(release_valid),.weight_release_ready(release_ready),.weight_release_epoch(rel_epoch),.weight_release_group(rel_group),.weight_release_global_q_head(rel_head),.weight_release_row(rel_row),.weight_release_slot_id(rel_slot),.weight_release_numeric_mode(rel_mode),.weight_wr_accept(wr_accept),.weight_rd_request(rd_request),.weight_rd_response(rd_response),.row_commit_count(row_commits),.pv_row_count(pv_rows),.weight_release_count(releases),.owner_error,.mask_error,.last_error,.mode_error,.numeric_error,.epoch_drop,.bank_conflict,.outstanding_max);
    cats_r4_weight_pv_wrapper u_wrap (.clk,.rst_n,.clear,.pv_row_valid,.pv_row_ready,.pv_row_epoch(pv_epoch),.pv_row_group(pv_group),.pv_row_global_q_head(pv_head),.pv_row_row(pv_row),.pv_row_slot_id(pv_slot),.pv_row_numeric_mode(pv_mode),.pv_row_inv_sum_fp32(pv_inv),.weight_rd_req_valid(rd_valid),.weight_rd_req_ready(rd_ready),.weight_rd_req_epoch(rd_epoch),.weight_rd_req_group(rd_group),.weight_rd_req_global_q_head(rd_head),.weight_rd_req_row(rd_row),.weight_rd_req_slot_id(rd_slot),.weight_rd_req_numeric_mode(rd_mode),.weight_rd_req_key(rd_key),.weight_rd_rsp_valid(rd_rsp_valid),.weight_rd_rsp_epoch(rsp_epoch),.weight_rd_rsp_group(rsp_group),.weight_rd_rsp_global_q_head(rsp_head),.weight_rd_rsp_row(rsp_row),.weight_rd_rsp_slot_id(rsp_slot),.weight_rd_rsp_numeric_mode(rsp_mode),.weight_rd_rsp_key(rsp_key),.weight_rd_rsp_mask(rsp_mask),.weight_rd_rsp_data(rsp_data),.row_start_valid,.row_start_ready,.row_start_inv_sum_fp32(row_start_inv_sum),.weight_valid,.weight_ready,.weight_key,.weight_mask,.weight_data,.weight_last,.pv_done_valid,.pv_done_ready,.weight_release_valid(wrapper_release_valid),.weight_release_ready(wrapper_release_ready),.weight_release_epoch(wrapper_rel_epoch),.weight_release_group(wrapper_rel_group),.weight_release_global_q_head(wrapper_rel_head),.weight_release_row(wrapper_rel_row),.weight_release_slot_id(wrapper_rel_slot),.weight_release_numeric_mode(wrapper_rel_mode),.rows_started,.weights_forwarded,.rows_released,.protocol_error_count(wrapper_errors));
    assign row_start_ready=1;
    assign release_valid=wrapper_release_valid; assign wrapper_release_ready=release_ready; assign rel_epoch=wrapper_rel_epoch; assign rel_group=wrapper_rel_group; assign rel_head=wrapper_rel_head; assign rel_row=wrapper_rel_row; assign rel_slot=wrapper_rel_slot; assign rel_mode=wrapper_rel_mode;
    task automatic tick; @(posedge clk); #1; endtask
    string root; integer i,seen;
    initial begin
      if(!$value$plusargs("REPLAY_ROOT=%s",root))$fatal(1,"REPLAY_ROOT required");
       $readmemh({root,"/rows.mem"},rows_mem); $readmemh({root,"/weights_fp32.mem"},weights); $readmemh({root,"/row_sum_fp32.mem"},sums_mem); $readmemh({root,"/row_inv_sum_fp32.mem"},inv_sums_mem);
      for(i=0;i<128;i=i+1) case_weights[i]=weights[128+i];
      start_epoch=16'ha203; start_group=rows_mem[1][15:11]; start_head=rows_mem[1][15:9]; start_row=rows_mem[1][8:2]; start_slot=rows_mem[1][1:0]; start_mode=1; start_sum=sums_mem[1]; start_inv=inv_sums_mem[1]; start_valid=0; weight_ready=1; pv_done_valid=0;
      repeat(4)tick();rst_n=1;repeat(2)tick();@(negedge clk);start_valid=1;while(!start_ready)tick();tick();@(negedge clk);start_valid=0;seen=0;
      while(seen<128)begin weight_ready=1;tick();if(weight_valid&&weight_ready)begin if(weight_key!=seen[6:0]||weight_mask!=(seen>start_row)||weight_data!=((seen>start_row)?32'd0:weights[128+seen]))$fatal(1,"weight mismatch key=%0d",seen);seen=seen+1;end end
      while(weights_forwarded<128)tick();@(negedge clk);pv_done_valid=1;while(!pv_done_ready)tick();tick();@(negedge clk);pv_done_valid=0;while(rows_released<1)tick();
      if(wr_accept!=128||row_commits!=1||pv_rows!=1||rd_request!=128||rd_response!=128||releases!=1||wrapper_errors!=0||owner_error!=0||mask_error!=0||last_error!=0||mode_error!=0||numeric_error!=0)$fatal(1,"C weight/PV integration counters mismatch");
      $display("PASS: CATS-R4 replay -> weight slot -> PV wrapper -> release");$finish;
    end
    initial begin repeat(20000)tick();$fatal(1,"weight/PV mem integration timeout");end
endmodule
